# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/FIR_filter_102stage_transpose/FIR_filterDesign/FIR_filterDesign.cache/wt [current_project]
set_property parent.project_path U:/FIR_filter_102stage_transpose/FIR_filterDesign/FIR_filterDesign.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog -library xil_defaultlib {
  U:/FIR_filter_102stage_transpose/FIR_filterDesign/FIR_filterDesign.srcs/sources_1/new/FIR_block.v
  U:/FIR_filter_102stage_transpose/FIR_filterDesign/FIR_filterDesign.srcs/sources_1/new/FIR_multiStage.v
}
read_xdc U:/FIR_filter_102stage_transpose/FIR_filterDesign/FIR_filterDesign.srcs/constrs_1/new/myconstraint.xdc
set_property used_in_implementation false [get_files U:/FIR_filter_102stage_transpose/FIR_filterDesign/FIR_filterDesign.srcs/constrs_1/new/myconstraint.xdc]

synth_design -top FIR_multiStage -part xc7z020clg484-1
write_checkpoint -noxdef FIR_multiStage.dcp
catch { report_utilization -file FIR_multiStage_utilization_synth.rpt -pb FIR_multiStage_utilization_synth.pb }
